services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nginx
    env_file: '.env'
    networks:
      - nginx-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf.template:ro
      - /var/www:/var/www:ro
      - ${HOME-/home}:/home/user:ro
      - ${MAIN_DIST-/usr/share/nginx/html}:/usr/share/nginx/html:ro
      - ${SSL_CERT}:/etc/ssl/certs/fullchain.pem:ro
      - ${SSL_KEY}:/etc/ssl/private/privkey.pem:ro
    command: sh -c "
      envsubst '${DOMAIN_NAME}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "

networks:
  nginx-network:
    driver: bridge
